openapi: 3.0.3
info:
  title: Squealer API
  description: squealer backend API
  version: '0.1'
servers:
  - url: '/api'

tags:
  - name: Auth
    description: 'Authenticate your squealer account'
  - name: User
    description: 'Handle the user account'

paths:
  /auth/register:
    post:
      tags:
        - Auth
      description: Register a new user
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: 'Operation successful'
        400:
          description: 'Bad Request'
        422:
          description: 'Unprocessable Entity'
  /auth/login:
    post:
      tags:
        - Auth
      description: Let the user login into their account
      summary: Log in existing user
      responses:
        200:
          description: Operation successful
          content:
            application/json:
              schema:
                type: string
  /auth/changepasswd:
    patch:
      tags:
        - Auth
      description: Change the user password
      summary: Change the user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
              format: password
              example: 'aVerySecurePasswd10'

      responses:
        200:
          description: Operation Successful

  /auth/resetpasswd/{email}:
    patch:
      tags:
        - Auth
      description: Changes the password of a non logged user
      summary: Recover lost password
      parameters:
        - in: path
          name: email
          required: true
          description: email of the user
          schema:
            type: string
            format: email
      responses:
        200:
          description: 'Operation Successful'

  /auth/delete:
    delete:
      tags:
        - Auth
      description: Delete the current user account
      summary: Delete the current user account
      responses:
        200:
          description: 'Operation Successful'

components:
  schemas:
    User:
      type: object
      required:
        - 'id'
        - 'username'
        - 'email'
        - 'firstname'
        - 'lastname'
        - 'password'
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
        firstname:
          type: string
        lastname:
          type: string
        password:
          type: string
          format: password
        type:
          type: string
          enum:
            - standard
            - verified
            - professional
            - moderator
        SMM:
          type: string
          format: uuid
          nullable: true
